language: python
python: 
  - "3.4"
virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-scipy
install:
  - pip install -r req.txt
script: python test_calculator.py
